; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_type = release
build_flags =
    -Os
    -fno-exceptions
    -fno-rtti
    -ffunction-sections
    -fdata-sections
    -Wl,--gc-sections
    -DCORE_DEBUG_LEVEL=0
    -DLOG_LOCAL_LEVEL=0
    -DOSFX_FUSION_MAX_ENTRIES=16
    -DOSFX_ID_MAX_ENTRIES=64
    -DOSFX_FUSION_MAX_SENSORS=8
    -DOSFX_TMPL_MAX_SENSORS=8
    -DOSFX_FUSION_MAX_VALS=16
    -DOSFX_FUSION_MAX_TAG_LEN=16
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit ST7735 and ST7789 Library @ ^1.10.3
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    https://github.com/OpenSynaptic/OSynaptic-FX.git
